name: hum2tabs
description: "A new Flutter project."
publish_to: none          # keep private
version: 1.0.0+1

environment:
  sdk: ^3.7.2              # matches your current toolchain

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.28.0   # audio recorder
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  wav: ^1.4.0              # pure-Dart PCM I/O
  tflite_flutter: ^0.11.0  # ⇐ NEW: offline ML runtime :contentReference[oaicite:0]{index=0}
  cupertino_icons: ^1.0.8
  pitch_detector_dart: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:                  # ⇐ NEW: bundle your (dummy) model
    - assets/models/dummy.tflite
