name: hum2tabs
description: "A new Flutter project."
publish_to: none          # keep private
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  wav: ^1.4.0
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/dummy.tflite
    - assets/models/pitch_crepe_micro.tflite
