name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Analyze • Build APK
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Check out repo
    - uses: actions/checkout@v4.2.2                 # 2024-10  :contentReference[oaicite:2]{index=2}

    # 2️⃣ JDK 17 for AGP 8.x / Flutter 3.29
    - name: Set up JDK 17
      uses: actions/setup-java@v4                   # 2024-11  :contentReference[oaicite:3]{index=3}
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Install Flutter
    - uses: subosito/flutter-action@v2.19.0         # 2025-04  :contentReference[oaicite:4]{index=4}
      with:
        channel: stable
        cache: true

    # 4️⃣ ▶ INSTALL NDK 29 & accept all licences  ◀
    - name: Install NDK 29 & accept licences
      run: |
        yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "ndk;29.0.13113456"
        yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

    # 5️⃣ Flutter doctor
    - run: flutter doctor -v

    # 6️⃣ Resolve packages
    - run: flutter pub get

    # 7️⃣ Static analysis
    - run: flutter analyze

    # 8️⃣ Build debug APK (smoke test)
    - run: flutter build apk --debug --no-shrink

    # 9️⃣ (optional) Upload APK artifact
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: debug-apk
    #     path: build/app/outputs/flutter-apk/app-debug.apk

    # 🔟 Tests – uncomment when ready
    # - run: flutter test --coverage
