name: Flutter CI

on:
  push:        { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 – Checkout source
    - uses: actions/checkout@v4                      # node-20 ready :contentReference[oaicite:1]{index=1}

    # 2 – Java 17 is the minimum AGP 8.x / Flutter 3.22-plus requires :contentReference[oaicite:2]{index=2}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    # 3 – Android SDK **and** NDK with licences auto-accepted
    - name: Set up Android SDK + NDK
      uses: android-actions/setup-android@v3         # auto-accepts licences :contentReference[oaicite:3]{index=3}
      with:
        # Everything you’ll actually need to compile/debug:
        packages: |
          platforms;android-34
          build-tools;34.0.0
          ndk;29.0.13113456                          # matches Gradle error
        accept-android-sdk-licenses: "yes"           # explicit for clarity

    # 4 – Flutter (cached)
    - uses: subosito/flutter-action@v2               # installs & caches Flutter :contentReference[oaicite:4]{index=4}
      with:
        channel: stable
        cache: true                                  # speeds up subsequent runs

    # 5 – Doctor, pub, analysis, tests (add back when they pass)
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter analyze
    # - run: flutter test --coverage                 # uncomment once green

    # 6 – Smoke-test build
    - name: Build debug APK
      run: flutter build apk --debug --no-shrink

    # 7 – Upload artefact (Actions v4 is mandatory Jan 2025) :contentReference[oaicite:5]{index=5}
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: hum2tabs-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 14
