name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build Debug APK
        run: flutter build apk --debug --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
