name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # checkout
      actions: read         # download other actions
      id-token: write       # required by v4 artifact actions
    steps:
      # 1 Checkout
      - uses: actions/checkout@v4                         # v4 is node20-ready :contentReference[oaicite:1]{index=1}

      # 2 Install Flutter
      - uses: subosito/flutter-action@v2                  # stable channel

      # 3 Doctor / pub / analysis / tests
      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --coverage

      # 4 Build a debug APK as a smoke-test
      - name: Build debug APK
        run: flutter build apk --debug --no-shrink

      # 5 Upload the build artefact — **v4** is required after Jan 2025
      - name: Upload APK
        uses: actions/upload-artifact@v4                  # new major version :contentReference[oaicite:2]{index=2}
        with:
          name: hum2tabs-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14                              # optional
