name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Analyze • Build APK
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Check out repo (v4)
    - uses: actions/checkout@v4.2.2   # latest stable  :contentReference[oaicite:3]{index=3}

    # 2️⃣ Install Java 17 (required by AGP 8.x / Flutter 3.29)
    - name: Set up JDK 17
      uses: actions/setup-java@v4      # GA Oct-2024  :contentReference[oaicite:4]{index=4}
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Install Flutter (stable channel)
    - uses: subosito/flutter-action@v2.19.0  # latest Apr-2025  :contentReference[oaicite:5]{index=5}
      with:
        channel: stable
        cache: true                # speed up builds

    # 4️⃣ Doctor (sanity)
    - name: Flutter doctor
      run: flutter doctor -v

    # 5️⃣ Resolve packages
    - name: Flutter pub get
      run: flutter pub get

    # 6️⃣ Static analysis (optional but fast)
    - name: Flutter analyze
      run: flutter analyze

    # 7️⃣ Build a debug APK as smoke test
    - name: Build Debug APK
      run: flutter build apk --debug --no-shrink

    # 8️⃣ (Optional) upload APK — uncomment when you need it
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

    # 9️⃣ Unit tests — keep disabled until tests are written
    # - name: Run tests
    #   run: flutter test --coverage
