name: Flutter CI

on:
  push:         { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 – Checkout
    - uses: actions/checkout@v4                                 # node-20 ready :contentReference[oaicite:3]{index=3}

    # 2 – JDK 17 (required by Flutter 3.22 / AGP 8) :contentReference[oaicite:4]{index=4}
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    # 3 – Android SDK + NDK with licences auto-accepted
    - uses: android-actions/setup-android@v3
      with:
        # ✅ Boolean, *not* "yes"
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: false

        # Extra packages your build complained about
        packages: |
          platforms;android-34
          build-tools;34.0.0
          ndk;29.0.13113456         # same revision Gradle asked for 
        # cmdline-tools-version stays default (12266719) :contentReference[oaicite:5]{index=5}

    # 4 – Flutter (with cache)
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true                               :contentReference[oaicite:6]{index=6}

    # 5 – Doctor / pub / lint
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter analyze

    # 6 – Smoke-test build
    - run: flutter build apk --debug --no-shrink

    # 7 – Upload artefact (Actions v4)
    - uses: actions/upload-artifact@v4
      with:
        name: hum2tabs-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 14
